version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./src:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./shared-files/nginx/:/var/log/nginx"
    ports:
      - "80:80"
      - "3000:443"
    depends_on:
      - php
      - db
  php:
    image: nanoninja/php-fpm:8.1
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./src:/var/www/html"
  bedrock-composer:
    image: "composer"
    volumes:
      - "./src:/app"
    command: install
  theme-composer:
    image: "composer"
    volumes:
      - "./src/web/app/themes/sage/:/app"
    command: install
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=wp
      - MYSQL_ROOT_PASSWORD=hola
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - "8989:3306"
    volumes:
      - "./shared-files/mysql:/var/lib/mysql"
  wpcli:
    depends_on:
      - web
    image: wordpress:cli-php8.1
    user: "1000:1000"
    command: tail -f /dev/null
    volumes:
      - "./src/:/var/www/html"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=mysql
      - WORDPRESS_DB_PASSWORD=mysql
      - WORDPRESS_DB_NAME=mysql
    profiles:
      - dev
